### Code by John Pan (260739619)
### Q1

In [97]:
import numpy as np
import copy as cp

### BFS implementation

In [123]:
class Node(): 
    def __init__(self,state,parent):
        self.state = state # current puzzle state
        self.parent = parent # previous state       
        # children node
        # Print path when goal found by tracing back using parent node

def printNodes(goalnode):
    nodestack = []
    while goalnode != None: # put the nodes into stack and pop to get history (LIFO)
        nodestack.insert(0,goalnode.state)
        goalnode = goalnode.parent
    while nodestack:
        print(nodestack.pop(0))

def moveL(state):
    i, j = np.where(state == 0)
    cpy = cp.deepcopy(state)
    tmpval = cpy[i, j-1] #value to the left of 0
    cpy[i,j] = tmpval
    cpy[i,j-1] = 0
    return cpy
    
def moveR(state):
    i, j = np.where(state == 0)
    cpy = cp.deepcopy(state)
    tmpval = cpy[i, j+1] #value to the right of 0
    cpy[i,j] = tmpval
    cpy[i,j+1] = 0
    return cpy

def moveD(state):
    i, j = np.where(state == 0)
    cpy = cp.deepcopy(state)
    tmpval = cpy[i+1, j] #value below 0
    cpy[i,j] = tmpval
    cpy[i+1,j] = 0
    return cpy

def moveU(state):
    i, j = np.where(state == 0)
    cpy = cp.deepcopy(state)
    tmpval = cpy[i-1, j] #value above 0
    cpy[i,j] = tmpval
    cpy[i-1,j] = 0
    return cpy 

def breadth_first_search(root_node, goal_state):
        
    queue = [root_node] #Initialize queue with current root
    visited = [] # record visited states

    while queue:

        cnode = queue.pop(0) # remove the first node in queue
        visited.append(tuple(cnode.state.reshape(1,6)[0])) # add to visited nodes, save as tuple to compare more easily

        # when the goal state is found, trace back to the root node and print out the path
        if np.array_equal(cnode.state,goal_state):
            printNodes(cnode)
            return True

        else:
            #check all possible positions to move
            state = cnode.state
            i, j = np.where(state == 0) 
            if i[0] == 0: # 0 in top row
                if j[0] == 0: #0 at top left corner
                    R = moveR(state)
                    D = moveD(state)
                    if tuple(R.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=R, parent=cnode)
                        queue.append(nnode1)
                    if tuple(D.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=D, parent=cnode)
                        queue.append(nnode2)
                elif j[0] == 1: #0 at top middle 
                    R = moveR(state)
                    D = moveD(state)
                    L = moveL(state)
                    if tuple(R.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=R, parent=cnode)
                        queue.append(nnode1)
                    if tuple(D.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=D, parent=cnode)
                        queue.append(nnode2)
                    if tuple(L.reshape(1,6)[0]) not in visited:
                        nnode3 = Node(state=L, parent=cnode)
                        queue.append(nnode3)
                else: #0 top right corner
                    D = moveD(state)
                    L = moveL(state)
                    if tuple(D.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=D, parent=cnode)
                        queue.append(nnode1)
                    if tuple(L.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=L, parent=cnode)
                        queue.append(nnode2)
            else: # 0 in bottom row
                if j[0] == 0: #0 at bottom left corner
                    R = moveR(state)
                    U = moveU(state)
                    if tuple(R.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=R, parent=cnode)
                        queue.append(nnode1)
                    if tuple(U.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=U, parent=cnode)
                        queue.append(nnode2)
                elif j[0] == 1: #0 at bottom middle
                    R = moveR(state)
                    U = moveU(state)
                    L = moveL(state)
                    if tuple(R.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=R, parent=cnode)
                        queue.append(nnode1)
                    if tuple(U.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=U, parent=cnode)
                        queue.append(nnode2)
                    if tuple(L.reshape(1,6)[0]) not in visited:
                        nnode3 = Node(state=L, parent=cnode)
                        queue.append(nnode3)
                else: #0 bottom right corner
                    L = moveL(state)
                    U = moveU(state)
                    if tuple(L.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=L, parent=cnode)
                        queue.append(nnode1)
                    if tuple(U.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=U, parent=cnode)
                        queue.append(nnode2)
    return False #end goal not found

In [124]:
root = np.array([1,4,2,5,3,0]).reshape(2,3)
goal_state = np.array([0,1,2,5,4,3]).reshape(2,3)
#print(root)
#print(goal_state)
root_node = Node(state = root, parent = None)
breadth_first_search(root_node, goal_state)

[[1 4 2]
 [5 3 0]]
[[1 4 2]
 [5 0 3]]
[[1 0 2]
 [5 4 3]]
[[0 1 2]
 [5 4 3]]


True

### Note that since we have unit cost, the uniform cost search algorithm would yield the exact same result as BFS above (same implementation).

### DFS Implementation (same as above, but with stack instead)

In [132]:
def depth_first_search(root_node, goal_state):
        
    stack = [root_node] #Initialize stack with current root
    visited = [] # record visited states

    while stack:

        cnode = stack.pop(0) # remove the first node in stack
        visited.append(tuple(cnode.state.reshape(1,6)[0])) # add to visited nodes, save as tuple to compare more easily

        # when the goal state is found, trace back to the root node and print out the path
        if np.array_equal(cnode.state,goal_state):
            printNodes(cnode)
            return True

        else:
            #check all possible positions to move
            state = cnode.state
            i, j = np.where(state == 0) 
            if i[0] == 0: # 0 in top row
                if j[0] == 0: #0 at top left corner
                    R = moveR(state)
                    D = moveD(state)
                    if tuple(R.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=R, parent=cnode)
                        stack.insert(0,nnode1)
                    if tuple(D.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=D, parent=cnode)
                        stack.insert(0,nnode2)
                elif j[0] == 1: #0 at top middle 
                    R = moveR(state)
                    D = moveD(state)
                    L = moveL(state)
                    if tuple(R.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=R, parent=cnode)
                        stack.insert(0,nnode1)
                    if tuple(D.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=D, parent=cnode)
                        stack.insert(0,nnode2)
                    if tuple(L.reshape(1,6)[0]) not in visited:
                        nnode3 = Node(state=L, parent=cnode)
                        stack.insert(0,nnode3)
                else: #0 top right corner
                    D = moveD(state)
                    L = moveL(state)
                    if tuple(D.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=D, parent=cnode)
                        stack.insert(0,nnode1)
                    if tuple(L.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=L, parent=cnode)
                        stack.insert(0,nnode2)
            else: # 0 in bottom row
                if j[0] == 0: #0 at bottom left corner
                    R = moveR(state)
                    U = moveU(state)
                    if tuple(R.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=R, parent=cnode)
                        stack.insert(0,nnode1)
                    if tuple(U.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=U, parent=cnode)
                        stack.insert(0,nnode2)
                elif j[0] == 1: #0 at bottom middle
                    R = moveR(state)
                    U = moveU(state)
                    L = moveL(state)
                    if tuple(R.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=R, parent=cnode)
                        stack.insert(0,nnode1)
                    if tuple(U.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=U, parent=cnode)
                        stack.insert(0,nnode2)
                    if tuple(L.reshape(1,6)[0]) not in visited:
                        nnode3 = Node(state=L, parent=cnode)
                        stack.insert(0,nnode3)
                else: #0 bottom right corner
                    L = moveL(state)
                    U = moveU(state)
                    if tuple(L.reshape(1,6)[0]) not in visited:
                        nnode1 = Node(state=L, parent=cnode)
                        stack.insert(0,nnode1)
                    if tuple(U.reshape(1,6)[0]) not in visited:
                        nnode2 = Node(state=U, parent=cnode)
                        stack.insert(0,nnode2)
    return False #end goal not found

In [133]:
root = np.array([1,4,2,5,3,0]).reshape(2,3)
goal_state = np.array([0,1,2,5,4,3]).reshape(2,3)
root_node = Node(state = root, parent = None)
depth_first_search(root_node, goal_state)

[[1 4 2]
 [5 3 0]]
[[1 4 0]
 [5 3 2]]
[[1 0 4]
 [5 3 2]]
[[0 1 4]
 [5 3 2]]
[[5 1 4]
 [0 3 2]]
[[5 1 4]
 [3 0 2]]
[[5 0 4]
 [3 1 2]]
[[0 5 4]
 [3 1 2]]
[[3 5 4]
 [0 1 2]]
[[3 5 4]
 [1 0 2]]
[[3 0 4]
 [1 5 2]]
[[0 3 4]
 [1 5 2]]
[[1 3 4]
 [0 5 2]]
[[1 3 4]
 [5 0 2]]
[[1 3 4]
 [5 2 0]]
[[1 3 0]
 [5 2 4]]
[[1 0 3]
 [5 2 4]]
[[0 1 3]
 [5 2 4]]
[[5 1 3]
 [0 2 4]]
[[5 1 3]
 [2 0 4]]
[[5 0 3]
 [2 1 4]]
[[0 5 3]
 [2 1 4]]
[[2 5 3]
 [0 1 4]]
[[2 5 3]
 [1 0 4]]
[[2 0 3]
 [1 5 4]]
[[0 2 3]
 [1 5 4]]
[[1 2 3]
 [0 5 4]]
[[1 2 3]
 [5 0 4]]
[[1 2 3]
 [5 4 0]]
[[1 2 0]
 [5 4 3]]
[[1 0 2]
 [5 4 3]]
[[0 1 2]
 [5 4 3]]


True

### Iterative Deepening Search Implementation (modified DFS to include depth limit)

In [130]:
def ID_search(root_node, goal_state):
    
    for dlim in range(5): #we know DFS took 4 states to solve
        stack = [root_node] #Initialize stack with current root
        visited = [] # record visited states
        depthstack = [0] # use stack to store the depth of each node, which matches the stack of nodes
        while stack:

            cnode = stack.pop(0) # remove the first node in stack
            d = depthstack.pop(0)
            visited.append(tuple(cnode.state.reshape(1,6)[0])) # add to visited nodes, save as tuple to compare more easily

            # when the goal state is found, trace back to the root node and print out the path
            if np.array_equal(cnode.state,goal_state):
                printNodes(cnode)
                return True

            elif d < dlim:
                #check all possible positions to move
                state = cnode.state
                i, j = np.where(state == 0) 
                if i[0] == 0: # 0 in top row
                    if j[0] == 0: #0 at top left corner
                        R = moveR(state)
                        D = moveD(state)
                        if tuple(R.reshape(1,6)[0]) not in visited:
                            nnode1 = Node(state=R, parent=cnode)
                            stack.insert(0,nnode1)
                            depthstack.insert(0,d+1)
                        if tuple(D.reshape(1,6)[0]) not in visited:
                            nnode2 = Node(state=D, parent=cnode)
                            stack.insert(0,nnode2)
                            depthstack.insert(0,d+1)
                    elif j[0] == 1: #0 at top middle 
                        R = moveR(state)
                        D = moveD(state)
                        L = moveL(state)
                        if tuple(R.reshape(1,6)[0]) not in visited:
                            nnode1 = Node(state=R, parent=cnode)
                            stack.insert(0,nnode1)
                            depthstack.insert(0,d+1)
                        if tuple(D.reshape(1,6)[0]) not in visited:
                            nnode2 = Node(state=D, parent=cnode)
                            stack.insert(0,nnode2)
                            depthstack.insert(0,d+1)
                        if tuple(L.reshape(1,6)[0]) not in visited:
                            nnode3 = Node(state=L, parent=cnode)
                            stack.insert(0,nnode3)
                            depthstack.insert(0,d+1)
                    else: #0 top right corner
                        D = moveD(state)
                        L = moveL(state)
                        if tuple(D.reshape(1,6)[0]) not in visited:
                            nnode1 = Node(state=D, parent=cnode)
                            stack.insert(0,nnode1)
                            depthstack.insert(0,d+1)
                        if tuple(L.reshape(1,6)[0]) not in visited:
                            nnode2 = Node(state=L, parent=cnode)
                            stack.insert(0,nnode2)
                            depthstack.insert(0,d+1)
                else: # 0 in bottom row
                    if j[0] == 0: #0 at bottom left corner
                        R = moveR(state)
                        U = moveU(state)
                        if tuple(R.reshape(1,6)[0]) not in visited:
                            nnode1 = Node(state=R, parent=cnode)
                            stack.insert(0,nnode1)
                            depthstack.insert(0,d+1)
                        if tuple(U.reshape(1,6)[0]) not in visited:
                            nnode2 = Node(state=U, parent=cnode)
                            stack.insert(0,nnode2)
                            depthstack.insert(0,d+1)
                    elif j[0] == 1: #0 at bottom middle
                        R = moveR(state)
                        U = moveU(state)
                        L = moveL(state)
                        if tuple(R.reshape(1,6)[0]) not in visited:
                            nnode1 = Node(state=R, parent=cnode)
                            stack.insert(0,nnode1)
                        if tuple(U.reshape(1,6)[0]) not in visited:
                            nnode2 = Node(state=U, parent=cnode)
                            stack.insert(0,nnode2)
                            depthstack.insert(0,d+1)
                        if tuple(L.reshape(1,6)[0]) not in visited:
                            nnode3 = Node(state=L, parent=cnode)
                            stack.insert(0,nnode3)
                            depthstack.insert(0,d+1)
                    else: #0 bottom right corner
                        L = moveL(state)
                        U = moveU(state)
                        if tuple(L.reshape(1,6)[0]) not in visited:
                            nnode1 = Node(state=L, parent=cnode)
                            stack.insert(0,nnode1)
                            depthstack.insert(0,d+1)
                        if tuple(U.reshape(1,6)[0]) not in visited:
                            nnode2 = Node(state=U, parent=cnode)
                            stack.insert(0,nnode2)
                            depthstack.insert(0,d+1)
    return False #end goal not found

In [131]:
root = np.array([1,4,2,5,3,0]).reshape(2,3)
goal_state = np.array([0,1,2,5,4,3]).reshape(2,3)
root_node = Node(state = root, parent = None)
ID_search(root_node, goal_state)

[[1 4 2]
 [5 3 0]]
[[1 4 2]
 [5 0 3]]
[[1 0 2]
 [5 4 3]]
[[0 1 2]
 [5 4 3]]


True